version: '2'
services:
    sipservice-app:
        image: sipservice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sipservice-mysql:3306/sipservice?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    sipservice-mysql:
        extends:
            file: mysql.yml
            service: sipservice-mysql
